# data source

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:hole
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

hole:
  jwt:
    secret: 6FLhmWAdj7
    expiration: 600000 #10min em milisegundos
    issuer: ProgramaSTARTER

  api:
    version: v1
    documentation: /swagger-ui/

  platform: development

security:
  oauth2:
    client:
      id: 1
      secret: 1



