flyway:
  user: databaseUser
  password: databasePassword
  url: jdbc:h2:mem:hole
  locations: filesystem:db/migration

spring:
  # jpa:
  #   hibernate:
  #     ddl-auto: none
  #   database-platform: org.hibernate.dialect.H2Dialect

  # datasource:
  #   # url: jdbc:mysql://localhost:3306/hole?createDatabaseIfNotExist=True
  #   url: jdbc:h2:mem:hole;DB_CLOSE_DELAY=-1
    # url: jdbc:h2:mem:hole
  #   username: sa
  #   password: ''
  #   driverClassName: org.h2.Driver #
    
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

hole:
  jwt:
    secret: 6FLhmWAdj7
    expiration: 600000 #10min em milisegundos
    issuer: ProgramaSTARTER

  api:
    version: v1
    documentation: /swagger-ui/

  platform: development

security:
  oauth2:
    client:
      id: 1
      secret: 1



