flyway:
  user: databaseUser
  password: databasePassword
  url: jdbc:h2:mem:hole
  locations: filesystem:db/migration

spring:    
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

hole:
  jwt:
    secret: 6FLhmWAdj7
    expiration: 600000 #10min em milisegundos
    issuer: ProgramaSTARTER

  api:
    version: v1
    documentation: /swagger-ui/

  platform: development

security:
  oauth2:
    client:
      id: 1
      secret: 1



