CREATE TABLE IF NOT EXISTS regiao (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  sigla VARCHAR (5),
  nome VARCHAR(25)
);

CREATE TABLE IF NOT EXISTS estado (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  uf VARCHAR(2) NOT NULL,
  nome VARCHAR(30) NOT NULL,
  regiao_id BIGINT NOT NULL,
  FOREIGN KEY (regiao_id) REFERENCES regiao(id)
);

CREATE TABLE IF NOT EXISTS cidade (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  estado_id BIGINT NOT NULL,
  FOREIGN KEY (estado_id) REFERENCES estado(id)
);

CREATE TABLE IF NOT EXISTS registro_buraco (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  descricao TEXT,
  latitude VARCHAR(20) NOT NULL,
  logitude VARCHAR(20) NOT NULL,
  cidade_id BIGINT NOT NULL,
  FOREIGN KEY (cidade_id) REFERENCES cidade(id)
);