

CREATE TABLE IF NOT EXISTS perfil (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL
);

INSERT INTO perfil(nome) VALUES
  ('ADMIN'),
  ('USUARIO');
 

CREATE TABLE IF NOT EXISTS usuario (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  perfil_id BIGINT NOT NULL,
  FOREIGN KEY (perfil_id) REFERENCES perfil(id)
);

